# each line is a individual package. "#" comments out a line.

# base system
base
sudo
vim
less
git
plocate
linux-rt
mkinitcpio
amd-ucode
linux-firmware-mediatek
linux-firmware-amdgpu
linux-firmware-realtek
turnstile-dinit
bash-completion
dhcpcd-dinit
btrfs-progs
grub-btrfs
efibootmgr
tmux
iptables
dosfstools
dbus-dinit
dbus-dinit-user
firewalld-dinit
acpid-dinit
chrony-dinit
snooze
dnsmasq-dinit
polkit
fail2ban-dinit
opensmtpd-dinit
openssh-dinit
openresolv
lm_sensors-dinit
syslog-ng-dinit
zramen-dinit
lxd-dinit
snapper
inotify-tools
mtools
lsof
seatd-dinit
logrotate
smartmontools
reflector
pacman-contrib
pipewire-pulse-dinit
wireplumber-dinit
pipewire-jack
pipewire-v4l2
pipewire-audio
pipewire-roc
pipewire-alsa
realtime-privileges
rtkit
rsync
atop
psmisc
ncdu
aide
python
apache
db
debuginfod
scx-scheds
