# each line is a individual package. "#" comments out a line.

# base system
base
sudo
ex-vi-compat
less
git
plocate
linux-rt
mkinitcpio
amd-ucode
linux-firmware-mediatek
linux-firmware-amdgpu
linux-firmware-realtek
bash-completion
btrfs-progs
efibootmgr
tmux
iptables
dosfstools 
ufw
fail2ban
dropbear
dropbear-scp
lm_sensors
snapper
snap-pac
lsof
smartmontools
reflector
pacman-contrib
pipewire-jack
rsync
atop
ncdu
python
nginx
incus-tools
umoci
cdrtools
apparmor
thin-provisioning-tools
lvm2
fwupd
python-dbus
python-gobject
udisks2
netctl
wireguard-tools
systemd-resolvconf
dialog
etc-update
openvswitch
